services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8001:8001"
      - "8501:8501"
    depends_on:
      - chromadb
    environment:
      - CHROMA_URL=http://chromadb:8000
      - OLLAMA_URL=http://host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"

  chromadb:
    container_name: chromadb
    image: chromadb/chroma:latest
    volumes:
      - chromadb_data:/chroma/chroma
    command: "--workers 1 --host 0.0.0.0 --port 8000 --proxy-headers --log-config chromadb/log_config.yml --timeout-keep-alive 30"
    environment:
      IS_PERSISTENT: true
    ports:
      - 8000:8000
    healthcheck:
      test:
        ["CMD", "/bin/bash", "-c", "cat < /dev/null > /dev/tcp/localhost/8001"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  chromadb_data:
